---
# This playbook will aquire/renew LetsEncrypt certificates using Route53 authentication
# and deploy them to the appropriate servers


- name: Initialize vars
  hosts: all
  tags:
    - always
  tasks:
    - name: include vars
      include_vars: "global_vars/config.yml"


# Section 1: initialization and enrollment
- name: Initialize SSL keys and Enroll with ACME
  hosts: all
  tags:
    - generate_pk
    - enroll
    - ACME_Enroll
  roles:
    - ACME_Enroll

# Section 2: ACME Verification and deployment of keys
- name: Generate CSRs and ACME challenges
  hosts: all
  tags:
    - verify
    - ACME_CSR
  roles:
    - ACME_CSR

# Section 3: Use R53 to verify challenges
- name: Verify ACME challenges with R53
  hosts: all
  tags:
    - verify
    - R53_Verify
  roles:
    - R53_Verify

- name: Verify ACME challenges
  hosts: all
  tags:
    - verify
    - ACME_Verify
  roles:
    - ACME_Verify
