#
# We run this once for every CSR we have
#
# loop_var:  "CSR"
# index_var: "CSR_idx"
#


- name: Fullfill ACME challenges in R53 for CSR CN:{{ CSR['item']['invocation']['module_args']['common_name'] }}
  community.aws.route53:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    hosted_zone_id: "{{ challenge.value['dns-01']['R53zoneID'] }}"
    record: "{{ challenge.value['dns-01']['record'] }}"
    type: TXT
    ttl: 60
    state: present
    # We could significantly speed things up by not waiting for DNS to propagate, but
    # we run the risk of not having the challenge ready in time for LE to verify it.
    wait: yes
    overwrite: yes
    value: "\"{{ challenge.value['dns-01']['resource_value'] }}\""
  loop: "{{ CSR['challenge_data'] | dict2items }}"
  loop_control:
    loop_var: "challenge"
    index_var: "challenge_idx"
  # While async would significantly speed things up, this module appears to break
  # async: 300
  # poll: 5

