#
# We run this once for each challenge
#
# loop_var:  "challenge"
# index_var: "challenge_idx"
#

- name: Fullfill ACME challenge in R53
  community.aws.route53:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    hosted_zone_id: "{{ challenge.value['dns-01']['R53zoneID'] }}"
    record: "{{ challenge.value['dns-01']['record'] }}"
    type: TXT
    ttl: 60
    state: present
    wait: yes
    value: "\"{{ challenge.value['dns-01']['resource_value'] }}\""
