---
# tasks file for ACME_Verify


- name: Let the challenge be validated and retrieve the cert and intermediate certificate
  become: true
  community.crypto.acme_certificate:
    modify_account: no
    account_key_src: "{{ ssl_pk_dir }}/{{ ssl_pk }}"
    src: "{{ item.item.filename }}"
    challenge: "{{ acme_challenge_type }}"
    acme_directory: "{{ acme_directory }}"
    acme_version: "{{ acme_version }}"
    remaining_days: "{{ acme_remaining_days }}"
    dest: "{{ crt_path }}/{{ item.item.item.commonName }}{{ ansible_date_time.iso8601_basic_short }}.crt"
    chain_dest: "{{ crt_path }}/{{ item.item.item.commonName }}{{ ansible_date_time.iso8601_basic_short }}-intermediate.crt"
    fullchain_dest: "{{ crt_path }}/{{ item.item.item.commonName }}{{ ansible_date_time.iso8601_basic_short }}-fullchain.crt"
    data: "{{ item }}"
  when: ACME_challenge is changed
  loop: "{{ ACME_challenge.results }}"
  register: result
# This works, but currently we use the same PK for our ACME account and our certs.  We need seperate PKs for each.



# Step 3: Check challenges & Save certificates
# - name: Let the challenge be validated and retrieve the cert and intermediate certificate
#   community.crypto.acme_certificate:
#     account_key_src: /etc/pki/cert/private/account.key
#     account_email: myself@sample.com
#     src: /etc/pki/cert/csr/sample.com.csr
#     cert: /etc/httpd/ssl/sample.com.crt
#     fullchain: /etc/httpd/ssl/sample.com-fullchain.crt
#     chain: /etc/httpd/ssl/sample.com-intermediate.crt
#     challenge: dns-01
#     acme_directory: https://acme-v01.api.letsencrypt.org/directory
#     remaining_days: 60
#     data: "{{ sample_com_challenge }}"
#   when: sample_com_challenge is changed


# Step 3.2: Optionally copy certs to local Ansible machine
#  - name: Copy certs to local ansible machine
#   ansible.builtin.fetch:
#     src: /etc/httpd/ssl/sample.com.crt
#   tags:
#     - never
#     - localCerts


# Step 3.5: Remove CSRs
